# Generated by Django 3.0.5 on 2021-09-20 09:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('partner_id', models.AutoField(primary_key=True, serialize=False)),
                ('partner_name', models.CharField(default=None, max_length=1000)),
                ('partner_gst', models.CharField(default=None, max_length=1000)),
                ('partner_phoneno', models.CharField(default=None, max_length=1000)),
                ('partner_email_id', models.CharField(default=None, max_length=1000)),
                ('partner_website', models.CharField(default=None, max_length=1000)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('member_id', models.AutoField(primary_key=True, serialize=False)),
                ('member_name', models.CharField(default=None, max_length=1000)),
                ('member_phone', models.CharField(default=None, max_length=1000)),
                ('member_email', models.CharField(default=None, max_length=1000)),
                ('added_by', models.CharField(default=None, max_length=100)),
                ('added_date', models.DateTimeField(default=datetime.datetime.now)),
                ('last_modified_by', models.CharField(default=None, max_length=100)),
                ('last_modified_date', models.DateTimeField(default=datetime.datetime.now)),
                ('partner_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Partner.Partners')),
            ],
        ),
    ]
